### ISSUE TITLE
Errors encountered while running voc.py

### ISSUE THREAD

**Issue by 904763189cy** [quwenjie/MultiGuard#2]
Not importing util

I don't know where it is.

Detailed error message：
Traceback (most recent call last):
  File "train.py", line 235, in <module>
    main()
  File "train.py", line 128, in main
    train_dataset = get_voc2007_train(args.input_size, MEAN, STD)
  File "/home/visionx/CIY/GithubProject/debias/MultiGuard-main/voc.py", line 269, in get_voc2007_train
    return Voc2007Classification("voc2007","trainval",tr)
  File "/home/visionx/CIY/GithubProject/debias/MultiGuard-main/voc.py", line 224, in __init__
    download_voc2007(self.root)
  File "/home/visionx/CIY/GithubProject/debias/MultiGuard-main/voc.py", line 133, in download_voc2007
    util.download_url(urls['devkit'], cached_file)
NameError: name 'util' is not defined

Could you help solve this problem? Thank you

**Comment by quwenjie** [comment]
Seems like there is some problems with the automatic download functionality of the code, to get the problem solved more promptly, please manually download VOC2007 dataset following the instructions in README file.
